### ISSUE TITLE
chrome 64似乎不能用了

### ISSUE THREAD

**Issue by AHwwh** [justjavac/ChromeSnifferPlus#97]

**Comment by justjavac** [comment]
```
Uncaught DOMException: Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules
    at chrome-extension://*************************/js/detector.js:566:67
    at chrome-extension://*************************/js/detector.js:615:3
```

https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet

**Comment by 303493624** [comment]
我也是，chrome  版本 64.0.3282.119（正式版本） （64 位）

**Comment by chaihongjun** [comment]
+1
